"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--!#6lh@6w6ct20*1#=dhwzag7&$)i&*pbn_4yd*=8j)#nsa_hd'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_celery_beat',
    
    # Third-party packages    
    'rest_framework',
    'rest_framework_simplejwt',
    
    # Local apps
    'notifications',
]

#Django HTTP Security, Validator
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

#this line instructions django of which database to use
#set to PostgreSQL in this case
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME', default='notification_db'),
        'USER': config('DB_USER', default='notification_user'),
        'PASSWORD' : config('DB_PASSWORD', default='my_secure_password'),
        'HOST' : config('DB_HOST', default='postgres_db'),
        'PORT' : config('DB_PORT', default='5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

#TIME_ZONE = 'Africa/Lagos'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

CELERY_TIMEZONE = 'UTC'
#CELERY_TIMEZONE = 'Africa/Lagos'
CELERY_ENABLE_UTC = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}

#means of authentication
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
     #   'rest_framework.authentication.BasicAuthentication'
    ),
    #use only JWT tokens
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',

    )

}

#network map for celery_beat and celery_worker to find redis
#redis actively listening on port 6379. '/0' is isolated workspace for task
CELERY_BROKER_URL = config('CELERY_BROKEN_URL' ,default='redis://127.0.0.1:6379/0')
CELERY_RESULT_BACKENDc = config('CELERY_RESULT_BACKEND', default='redis://127.0.0.1:6379/0')

#Modern Django 6.1 Email Infrastructure Settings
MAILERS = {
        'default' :{
                "BACKEND" : "django.core.mail.backends.console.EmailBackend",
        },        
}

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'noreply@notificationengine.com'


CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

#GMAIL SMTP mail server configuration 
MAILERS = {
    "default": {
        "BACKEND": "django.core.mail.backends.smtp.EmailBackend",
    },
}

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 465
EMAIL_USE_TLS = False
EMAIL_USE_SSL =True


#issue:  OSError:[Errno 101] Network is unreachable (ipv6 mismatch) 
# fix - force python to use universal IPV4 Network Protocol only
import socket
socket.getaddrinfo = lambda host, port, family=0, type=0, proto=0, flags=0: \
    _getaddrinfo(host, port, socket.AF_INET, type, proto, flags) if family == 0 else _getaddrinfo(host, port, family, type, proto, flags)
_getaddrinfo = socket._socket.getaddrinfo


EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = config('EMAIL_HOST_USER')

