# Generated by Django 6.1 on 2026-08-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationjob',
            name='secret_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
