# Generated by Django 6.1 on 2026-08-10 20:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationjob_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationjob',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
